#!/bin/bash

source $HOME/zcmd/devutils/default-docker-env.txt
source $HOME/zcmd/devutils/function-library/check-context.bash

lib_isMachineImageFolder
if [ $? -ne 0 ]; then
    echo "ERROR: The command must be invoked from a valid machine context folder."
    exit 2
fi

#Make sure we build using the latest FROM image
FROMVALUE=$(cat Dockerfile | grep "FROM " |  awk '{print $NF}')
echo
echo "... FROM value in Dockerfile=$FROMVALUE"
docker pull $FROMVALUE
echo
sleep 2

source machine.env
echo "IMAGE NAME = ${LOCAL_IMAGE_NAME}"
TAGNAME=$1
if [ -z "$TAGNAME" ]; then
    echo "-- NO TAG NAME (Docker will use tag 'latest')"
    CMD="docker build --rm -t local/${LOCAL_IMAGE_NAME} ."
else
    echo "TAG NAME = $TAGNAME"
    CMD="docker build --rm -t local/${LOCAL_IMAGE_NAME}:${TAGNAME} ."
fi

PWD=$(pwd)
if [ -f "${PWD}/DEPRECATED.txt" ]; then
    echo
    echo "WARNING: ${PWD} is DEPRECATED"
    echo
    echo "==========================================================================="
    echo
    cat ${PWD}/DEPRECATED.txt
    echo
    echo "==========================================================================="
    echo
    echo "PRESS CTRL-C now to ABORT else ENTER to continue"
    read
    echo
fi

echo $CMD
eval $CMD
echo