#!/bin/bash

source $HOME/zcmd/devutils/default-docker-env.txt
source $HOME/zcmd/devutils/function-library/check-context.bash

lib_isMachineImageFolder
if [ $? -ne 0 ]; then
    echo "ERROR: The command must be invoked from a valid machine context folder."
    exit 2
fi

source machine.env

if [ ! -z "$1" ]; then
    CONTAINERNAME=$1
    TAGNAME=$2
else
    CONTAINERNAME=${LOCAL_IMAGE_NAME}
    TAGNAME="latest"
fi
if [ -z "$TAGNAME" ]; then
    FQ_CONTAINER_IMAGENAME="local/${LOCAL_IMAGE_NAME}"
else
    FQ_CONTAINER_IMAGENAME="local/${LOCAL_IMAGE_NAME}:${TAGNAME}"
fi

echo "Create a container of the ${FQ_CONTAINER_IMAGENAME} image ..."

CMD="docker create -ti --name ${CONTAINERNAME} ${FQ_CONTAINER_IMAGENAME}"
echo $CMD
eval $CMD
docker ps -a


