#!/bin/bash

source $HOME/zcmd/devutils/default-docker-env.txt
source $HOME/zcmd/devutils/function-library/check-context.bash

lib_isMachineImageFolder
if [ $? -ne 0 ]; then
    echo "ERROR: The command must be invoked from a valid machine context folder."
    exit 2
fi

source machine.env

WHICHJQ=$(which jq)
if [ -z "$WHICHJQ" ]; then
    HASJQ="NO"
    JQPART=""
else
    HASJQ="YES"
    JQPART=" | jq"
fi

echo
echo "Listing of all local TAGS for '${PUBLIC_IMAGE_NAME}' ..."
CMD="docker image ls | grep ${PUBLIC_IMAGE_NAME}"
echo CMD=$CMD
eval $CMD

echo

echo "Listing of all shared TAGS for '${PUBLIC_IMAGE_NAME}' ..."
CMD="curl -X GET ${PRIVATE_DOCKER_FULL_REGISTRY_URL}/v2/${PUBLIC_IMAGE_NAME}/tags/list $JQPART"
echo CMD=$CMD
eval $CMD
echo





