#!/bin/bash
ZCMD_VERSIONINFO="20190728.2"
DASH_HELP_OPTION="--help"
DASH_VERSION_OPTION="--version"
DASH_ENV_NAME_OPTION="--environment-name"
DASH_ENV_INFO_OPTION="--environment-info"
DASH_ENV_INFO_SHORT_OPTION="-ei"

#Do they just want version info?
if [ "${DASH_VERSION_OPTION}" = "$1" ]; then
    #Important ONLY output the version string!
    echo $ZCMD_VERSIONINFO
    exit 0
fi

#Check for required environment vars
if [ -z "$ZCMD_HOME" ]; then
    echo "Aborting $0 v$ZCMD_VERSIONINFO"
    echo "##############################################################################"
    echo "ERROR: Configuration problem! Missing required ZCMD_HOME environment variable!"
    echo "TIP: Update your .bashrc to set it to the location of your zcmd folder."
    echo "     export ZCMD_HOME=thepath"
    echo "##############################################################################"
    echo
    exit 2
fi

source $ZCMD_HOME/devutils/default-docker-env.txt

if [ "${DASH_ENV_NAME_OPTION}" = "$1" ]; then
    #Important that there be NO OTHER text in the output!
    if [ -z "$ENVIRONMENT_NAME" ]; then
        #Provide a name that gives a clue to the error!
        WHOAMI=$(whoami)
        HOSTNAME=$(hostname)
        echo "ZCMD-ERROR-MISSING-ENVIRONMENT_NAME-${HOSTNAME}-${WHOAMI}"
        exit 2
    fi
    echo "$ENVIRONMENT_NAME"
    exit 0
fi

if [ "${DASH_ENV_INFO_OPTION}" = "$1" ] || [ "${DASH_ENV_INFO_SHORT_OPTION}" = "$1" ]; then
    echo "ZCMD_VERSIONINFO            = $ZCMD_VERSIONINFO"
    echo "ZCMD_TEAM_ENV_VERSIONINFO   = $ZCMD_TEAM_ENV_VERSIONINFO"
    echo "ZCMD_CUSTOM_ENV_VERSIONINFO = $ZCMD_CUSTOM_ENV_VERSIONINFO"
    echo
    echo "IS_PRODUCTION       = $IS_PRODUCTION"
    echo "ENVIRONMENT_CONTEXT = $ENVIRONMENT_CONTEXT"
    echo "ENVIRONMENT_NAME    = $ENVIRONMENT_NAME"
    exit 0
fi

source $HOME/zcmd/devutils/function-library/check-context.bash 

PWD=$(pwd)
HELPERSROOTPATH="$HOME/zcmd/devutils/zcmd_helpers"
STACK_COMMANDS=$(cd $HELPERSROOTPATH/stack && ls)
MACHINE_COMMANDS=$(cd $HELPERSROOTPATH/machine && ls)
GLOBAL_COMMANDS=$(cd $HELPERSROOTPATH/global && ls)

STACK_ALIAS_COMMANDS=$(cd $HELPERSROOTPATH/stack/.command-alias && ls)
MACHINE_ALIAS_COMMANDS=$(cd $HELPERSROOTPATH/machine/.command-alias && ls)
GLOBAL_ALIAS_COMMANDS=$(cd $HELPERSROOTPATH/global/.command-alias && ls)

function getCommandAliasContent()
{
    #Using tr to remove strange trash showing up for unknown reasons in the string sometimes
    local CONTEXT_NAME=$1    
    local COMMAND_NAME=$2
    local CLEAN_CMDNAME=$(echo $COMMAND_NAME | tr ";" " " | tr "''" " ")
    local FULL_ALIAS_PATH="$HELPERSROOTPATH/${CONTEXT_NAME}/.command-alias/${COMMAND_NAME}"
    local CLEAN_PATH=$(echo $FULL_ALIAS_PATH | tr ";" " " | tr "''" " ")
    if [ ! -f "${CLEAN_PATH}" ]; then
        echo ""
    else    
        echo $(cat $CLEAN_PATH)
    fi
}

function showUsage()
{
    local CONTEXT_NAME=$1
    echo " "
    echo "Usage: zcmd COMMAND [optional command arguments]"
    echo
    if [ -z "$CONTEXT_NAME" ] || [ "stack" = "$CONTEXT_NAME" ] || [ "showall" = "$CONTEXT_NAME" ]; then
        echo "STACK COMMAND options (work from stack folders) ..."
        export IFS=";"
        ALL_COMMANDS=$(echo $STACK_COMMANDS | tr "\n" ";") 
        for word in $ALL_COMMANDS; do
            local CLEAN_CMDNAME=$(echo $word | tr ";" " " | tr "''" " ")
            echo "   $CLEAN_CMDNAME"
        done
        echo
        if [ ! -z "$STACK_ALIAS_COMMANDS" ]; then
            echo "   And STACK alias commands ..."
            ALL_COMMANDS=$(echo $STACK_ALIAS_COMMANDS | tr "\n" ";") 
            for word in $ALL_COMMANDS; do
                local CLEAN_CMDNAME=$(echo $word | tr ";" " " | tr "''" " ")
                local ALIAS_CONTENT=$(getCommandAliasContent "stack" "$CLEAN_CMDNAME")
                echo "     $CLEAN_CMDNAME = $ALIAS_CONTENT"
            done
            echo
        fi
    fi
    if [ -z "$CONTEXT_NAME" ] || [ "machine" = "$CONTEXT_NAME" ] || [ "showall" = "$CONTEXT_NAME" ]; then
        echo "MACHINE COMMAND options (work from machine folders) ..."
        export IFS=";"
        ALL_COMMANDS=$(echo $MACHINE_COMMANDS | tr "\n" ";") 
        for word in $ALL_COMMANDS; do
            local CLEAN_CMDNAME=$(echo $word | tr ";" " " | tr "''" " ")
            echo "   $CLEAN_CMDNAME"
        done
        echo
        if [ ! -z "$MACHINE_ALIAS_COMMANDS" ]; then
            echo "   And MACHINE alias commands ..."
            ALL_COMMANDS=$(echo $MACHINE_ALIAS_COMMANDS | tr "\n" ";") 
            for word in $ALL_COMMANDS; do
                local CLEAN_CMDNAME=$(echo $word | tr ";" " " | tr "''" " ")
                local ALIAS_CONTENT=$(getCommandAliasContent "machine" "$CLEAN_CMDNAME")
                echo "     $CLEAN_CMDNAME = $ALIAS_CONTENT"
            done
            echo
        fi
    fi
    echo "GLOBAL COMMAND options (work from any folder) ..."
    ALL_COMMANDS=$(echo $GLOBAL_COMMANDS | tr "\n" ";") 
    for word in $ALL_COMMANDS; do
        local CLEAN_CMDNAME=$(echo $word | tr ";" " " | tr "''" " ")
        echo "   $CLEAN_CMDNAME"
    done
    echo
    if [ ! -z "$GLOBAL_ALIAS_COMMANDS" ]; then
        echo "   And GLOBAL alias commands ..."
        ALL_COMMANDS=$(echo $GLOBAL_ALIAS_COMMANDS | tr "\n" ";") 
        for word in $ALL_COMMANDS; do
            local CLEAN_CMDNAME=$(echo $word | tr ";" " " | tr "''" " ")
            local ALIAS_CONTENT=$(getCommandAliasContent "global" "$CLEAN_CMDNAME")
            echo "     $CLEAN_CMDNAME = $ALIAS_CONTENT"
        done
        echo
    fi
    echo
    echo "OTHER options ..."
    echo "$DASH_HELP_OPTION [COMMAND_NAME]"
    echo "$DASH_VERSION_OPTION"
    echo "$DASH_ENV_NAME_OPTION"
    echo "$DASH_ENV_INFO_OPTION, $DASH_ENV_INFO_SHORT_OPTION"
    echo " "
}

function showFancyHelp()
{
    local HELP4CMD=$1
    local CONTEXT_NAME=$2   
    local LOCK_CONTEXT_NAME=$3

    if [ ! -f "$HELPERSROOTPATH/${CONTEXT_NAME}/${HELP4CMD}" ]; then
        local ALIAS_CONTENT=$(getCommandAliasContent "$CONTEXT_NAME" "$HELP4CMD")
        if [ ! -z "$ALIAS_CONTENT" ]; then
            echo "Command '${HELP4CMD}' is a '${CONTEXT_NAME}' alias for the following command ..."
            echo ""
            echo "  zcmd $ALIAS_CONTENT"
            echo ""
            exit 0
        fi
        if [ "NO" = "$LOCK_CONTEXT_NAME" ]; then
            #Look everywhere
            local ALL_CONTEXT=( "stack" "machine" "global" )
            local GOT_HIT="NO"
            for CONTEXT_NAME in "${ALL_CONTEXT[@]}"
            do
                echo "Searching ${CONTEXT_NAME} context for help on '${HELP4CMD}' ..."
                if [ -f "${HELPERSROOTPATH}/${CONTEXT_NAME}/${HELP4CMD}" ]; then
                    GOT_HIT="YES"
                    break
                fi
                local ALIAS_CONTENT=$(getCommandAliasContent "$CONTEXT_NAME" "$HELP4CMD")
                if [ ! -z "$ALIAS_CONTENT" ]; then
                    echo "This is a ${CONTEXT_NAME} COMMAND ALIAS for the following command ..."
                    echo ""
                    echo "  zcmd $ALIAS_CONTENT"
                    echo ""
                    exit 0
                fi
            done
            if [ "NO" = "$GOT_HIT" ]; then
                #Undefined command!
                echo
                echo "BAD HELP ARGUMENT!  There is no command '$HELP4CMD'!"
                echo
                echo "Showing general help ..."
                showUsage "showall"
                echo " "
                exit 2
            fi
        fi
    fi    

    HELPFILENAME="${HELP4CMD}.help.txt"
    HELPFILEDIR="${HELPERSROOTPATH}/${CONTEXT_NAME}/.help-text"
    HELPFILEPATH="${HELPFILEDIR}/${HELPFILENAME}"
    if [ ! -f "$HELPFILEPATH" ]; then
        echo
        if [ ! -z "$HELP4CMD" ]; then
            #Tell them there is no file matching that command yet
            echo " "
            echo "Did NOT find $HELPFILEPATH"
            echo
        fi
        echo "Currently existing '${CONTEXT_NAME}' context help files are ..."
        echo "*** Start of existing help files ***"
        ls $HELPFILEDIR
        echo "*** End of existing help files ***"
        echo
        exit 2
    else
        #Show the file contents
        echo
        echo "Found help for zcmd ${HELP4CMD} in '${CONTEXT_NAME}' context ..."
        echo " "
        echo "==============================================================================="
        cat $HELPFILEPATH
        echo "==============================================================================="
        echo
        exit 0
    fi
}

#Trap param BEFORE we output any text
if [ "JUST_SHOW_OPTIONS" = "$1" ]; then
    #NOTE -- This output is used by command completion logic!
    lib_isRuntimeStackFolder
    if [ $? -eq 0 ]; then
        echo $DASH_HELP_OPTION $STACK_COMMANDS
    else
        lib_isMachineImageFolder
        if [ $? -eq 0 ]; then
            echo $DASH_HELP_OPTION $MACHINE_COMMANDS
        fi
    fi
    echo $DASH_HELP_OPTION $GLOBAL_COMMANDS
    exit 0
fi

#Tell the user we are running
echo "# Started ZCMD ($0) v$ZCMD_VERSIONINFO ..."
echo "# ... invoked from $PWD"

#Set the CONTEXT_NAME variable
lib_isRuntimeStackFolder
if [ $? -eq 0 ]; then
    CONTEXT_NAME="stack"
else
    lib_isMachineImageFolder
    if [ $? -eq 0 ]; then
        CONTEXT_NAME="machine"
    else
        CONTEXT_NAME="global"
    fi
fi

if [ -z "$1" ]; then
    echo " "
    echo "NO COMMAND SPECIFIED"
    showUsage "$CONTEXT_NAME"
    exit 2
fi

#Do they want fancy help?
if [ "$DASH_HELP_OPTION" = "$1" ]; then

    #Yes, they want fancy help!
    HELP4CMD="$2"
    if [ -z "$HELP4CMD" ]; then
        echo " "
        echo "Showing general help ..."
        showUsage "showall"
        echo " "
        exit 0
    fi
    LOCK_CONTEXT_NAME="NO"
    if [ "machine" = "$HELP4CMD" ]; then
        LOCK_CONTEXT_NAME="YES"
        CONTEXT_NAME="$HELP4CMD"
        HELP4CMD="$3"
    fi
    if [ "stack" = "$HELP4CMD" ]; then
        LOCK_CONTEXT_NAME="YES"
        CONTEXT_NAME="$HELP4CMD"
        HELP4CMD="$3"
    fi
    if [ "global" = "$HELP4CMD" ]; then
        LOCK_CONTEXT_NAME="YES"
        CONTEXT_NAME="$HELP4CMD"
        HELP4CMD="$3"
    fi

    #Show specific help, if it exists
    showFancyHelp "${HELP4CMD}" "${CONTEXT_NAME}" "${LOCK_CONTEXT_NAME}"  

fi

#Because we cannot pass $@ to function
TOPARG2=$2
TOPARG3=$3
TOPARG4=$4
TOPARG5=$5
TOPARG6=$6
TOPARG7=$7
TOPARG8=$8
TOPARGTOOMANY=$9

if [ ! -z "$TOPARGTOOMANY" ]; then
    #At lest tell them we are ignoring the extra arguments
    echo ""
    echo "#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo "#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo "#!!                                                 !!"
    echo "#!! WARNING TOO MANY ARGUMENTS PASSED TO ZCMD!!     !!"
    echo "#!!                                                 !!"
    echo "#!! IGNORING $TOPARGTOOMANY"
    echo "#!!                                                 !!"
    echo "#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo "#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
fi

function runCommand()
{
    local CONTEXT_NAME=$1
    local COMMAND_NAME=$2
    local FULL_COMMAND="$COMMAND_NAME $TOPARG2 $TOPARG3 $TOPARG4 $TOPARG5 $TOPARG6 $TOPARG7 $TOPARG8"

    if [ ! -f "$HELPERSROOTPATH/${CONTEXT_NAME}/${COMMAND_NAME}" ]; then
        #See if we have an alias
        local ALIAS_CONTENT=$(getCommandAliasContent "$CONTEXT_NAME" "$COMMAND_NAME")
        if [ ! -z "$ALIAS_CONTENT" ]; then
            echo "# Alias content for '$COMMAND_NAME' is $ALIAS_CONTENT"
            local FULL_COMMAND="$ALIAS_CONTENT $TOPARG2 $TOPARG3 $TOPARG4 $TOPARG5 $TOPARG6 $TOPARG7 $TOPARG8"
        else
            CONTEXT_NAME='global'
            if [ ! -f "$HELPERSROOTPATH/${CONTEXT_NAME}/${COMMAND_NAME}" ]; then
                #Undefined command!
                return 2
            fi
        fi    
    fi

    echo "#Will now launch ${CONTEXT_NAME} context command ${COMMAND_NAME} from folder $(pwd) ..."
    COMPLETE_COMMAND="$HELPERSROOTPATH/${CONTEXT_NAME}/$FULL_COMMAND"
    echo "#>>> $COMPLETE_COMMAND"
    (cd $(pwd) && eval "$COMPLETE_COMMAND")
    return $?
}

lib_isRuntimeStackFolder
if [ $? -eq 0 ]; then

    echo " "
    runCommand "stack" $1
    CMD_STATUS=$?
    if [ $CMD_STATUS -gt 1 ]; then
        if [ $CMD_STATUS -gt 10 ]; then
            #This probably not an error of zcmd usage
            echo "ERROR CODE: $CMD_STATUS"
            exit $CMD_STATUS
        else
            #Might be an error of zcmd usage
            echo " "
            echo "ERROR INVALID RUNTIME STACK CONTEXT COMMAND: $@"
            showUsage "stack"
            exit 2
        fi
    fi
    echo " "

else

    lib_isMachineImageFolder
    if [ $? -eq 0 ]; then
        echo " "
        runCommand "machine" $1
        CMD_STATUS=$?
        if [ $CMD_STATUS -gt 1 ]; then
            echo " "
            echo "ERROR INVALID MACHINE IMAGE CONTEXT COMMAND: $@"
            showUsage "machine"
            exit 2
        fi
        echo " "
    else
        #Just global commands allowed
        echo " "
        runCommand "global" $1
        CMD_STATUS=$?
        if [ $CMD_STATUS -gt 1 ]; then
            echo " "
            echo "ERROR INVALID GLOBAL CONTEXT COMMAND: $@"
            showUsage "global"
            exit 2
        fi
        echo " "
    fi

fi
    
#If we are here we had success
exit 0
