#!/bin/bash

VERSIONINFO="20190222.2"
echo "Started $0 v$VERSIONINFO"
echo "USAGE: import-assets-subset RAWSUFFIX [PROJECTNAME]"
echo

source $HOME/zcmd/devutils/default-docker-env.txt
source $HOME/zcmd/devutils/function-library/check-context.bash

#($HOME/zcmd/devutils/zc-check-is-stack-folder.sh)
lib_isRuntimeStackFolder
if [ $? -ne 0 ]; then
    echo "ERROR: The command must be invoked from a valid stack context folder."
    exit 2
fi
ZCMD_LAUNCHDIR=$(pwd)
source ./stack.env


if [ ! -z "$2" ]; then
    echo "Using PROJECT_NAME as '$2' instead of '${PROJECT_NAME}'"
    PROJECT_NAME="$2"
else
    if [ ! -z "$LEGACY_PROJECT_NAME" ]; then
        PROJECT_NAME=$LEGACY_PROJECT_NAME
        echo "Using standard LEGACY project name as prefix"
    else
        PROJECT_NAME=$PROJECT_NAME
        echo "Using standard project name as prefix"
    fi
fi
echo "  PROJECT_NAME=$PROJECT_NAME"


if [ ! -z "$WEB_DOCROOT_PATH" ]; then
    #Do the new hotness way (bind baby!)
    if [ -z "$WEB_DOCROOT_PATH" ]; then
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        echo "FATAL ERROR -- MISSING WEB_DOCROOT_PATH env var!!!"
        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        exit 2
    fi

    $HOME/zcmd/devutils/zc-export-app-assets-to-path.sh $PROJECT_NAME $WEB_DOCROOT_PATH
# else
#     #Do the OLD UGLY WAY AND FEEL BAD DOING IT!
#     echo "NOTE: Using old ugly WEB_FILES_VOLUME_NAME name approach"
#     if [ -z "$WEB_FILES_VOLUME_NAME" ]; then
#         echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
#         echo "FATAL ERROR -- MISSING WEB_FILES_VOLUME_NAME env var!!!"
#         echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
#         exit 2
#     fi
#     $HOME/zcmd/devutils/zc-import-app-assets.sh $PROJECT_NAME $WEB_FILES_VOLUME_NAME $RAWSUFFIX
fi
STATUS_CD=$?
if [ $STATUS_CD -ne 0 ]; then
    echo "FAILED $0 [CODE=$STATUS_CD]"
    exit $STATUS_CD
fi

