#!/bin/bash
ACTION="up"

source $HOME/zcmd/devutils/default-docker-env.txt
source $HOME/zcmd/devutils/function-library/check-context.bash

lib_isRuntimeStackFolder
if [ $? -ne 0 ]; then
    echo "ERROR: The command must be invoked from a valid stack context folder."
    exit 2
fi
ZCMD_LAUNCHDIR=$(pwd)
source ./stack.env

PWD=$(pwd)
if [ -f "${PWD}/DEPRECATED.txt" ]; then
    echo
    echo "WARNING: ${PWD} is DEPRECATED"
    echo
    echo "==========================================================================="
    echo
    cat ${PWD}/DEPRECATED.txt
    echo
    echo "==========================================================================="
    echo
    sleep 2
fi

#Start our network if not already started

THISFOLDERNAME=${PWD##*/}
if [ ! "admin" = "$THISFOLDERNAME" ]; then
    echo "Lets check on admin stack!"
    eval "$HOME/zcmd/devutils/zc-start-admin_webnet.sh $CUSTOM_ADMIN_STACK_PATH"
else
    echo "...already in $THISFOLDERNAME stack!"
fi

#Start PREREQUISITE_STACK_PATHS
if [ ! -z "$PREREQUISITE_STACK_PATHS" ]; then
    #TODO --- Allow for colon delimited paths!!!!
    echo
    echo "PREREQUISITE_STACK_PATHS=$PREREQUISITE_STACK_PATHS"
    echo
    (cd $PREREQUISITE_STACK_PATHS && zcmd up)
    echo
    #Small pause
    sleep 2
    echo "... Done launching all prerequisite stacks"
    echo
fi

#Launch our stack
echo "$ACTION $1 $2"
(cd $(pwd) && $HOME/zcmd/devutils/zc-compose.sh $ACTION $1)


